// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9ItEZGXaPNCrTPAE24TVRoxYctaFkBic',
    appId: '1:8154300151:web:4f3da3b0062a0c6de69df2',
    messagingSenderId: '8154300151',
    projectId: 'castly-57947',
    authDomain: 'castly-57947.firebaseapp.com',
    storageBucket: 'castly-57947.firebasestorage.app',
    measurementId: 'G-YQCBM869ZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-9e_2fXryOELI5wbHGarYt_g_mNA7tCQ',
    appId: '1:8154300151:android:f6b641eeac340ec7e69df2',
    messagingSenderId: '8154300151',
    projectId: 'castly-57947',
    storageBucket: 'castly-57947.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHVtGA03Z83QCQPdlyB-YCdR7-sbCkZDA',
    appId: '1:8154300151:ios:1adefd85fab13ab5e69df2',
    messagingSenderId: '8154300151',
    projectId: 'castly-57947',
    storageBucket: 'castly-57947.firebasestorage.app',
    iosBundleId: 'com.example.castly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHVtGA03Z83QCQPdlyB-YCdR7-sbCkZDA',
    appId: '1:8154300151:ios:1adefd85fab13ab5e69df2',
    messagingSenderId: '8154300151',
    projectId: 'castly-57947',
    storageBucket: 'castly-57947.firebasestorage.app',
    iosBundleId: 'com.example.castly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9ItEZGXaPNCrTPAE24TVRoxYctaFkBic',
    appId: '1:8154300151:web:f61079bcf3aeb93ce69df2',
    messagingSenderId: '8154300151',
    projectId: 'castly-57947',
    authDomain: 'castly-57947.firebaseapp.com',
    storageBucket: 'castly-57947.firebasestorage.app',
    measurementId: 'G-D84QNNX537',
  );
}
